name: Generate contributors list

on:
  push:
    branches:
      - main

jobs:
  # SEE https://github.com/marketplace/actions/contribute-list
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@83ea0b4f1ac928fbfe88b9e8460a932a528eb79f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
