name: depup
on:
  schedule:
    - cron: "14 14 * * *" # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]
  workflow_dispatch:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup/with-pr@v1
        with:
          file: action.yml
          version_name: reviewdog_version
          repo: reviewdog/reviewdog
          labels: "bump:minor"
